# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

AtA <- function(x) {
    .Call('_sptpsar_AtA', PACKAGE = 'sptpsar', x)
}

AAt <- function(x) {
    .Call('_sptpsar_AAt', PACKAGE = 'sptpsar', x)
}

lltA <- function(x) {
    .Call('_sptpsar_lltA', PACKAGE = 'sptpsar', x)
}

lltAinv <- function(x) {
    .Call('_sptpsar_lltAinv', PACKAGE = 'sptpsar', x)
}

detlltA <- function(x) {
    .Call('_sptpsar_detlltA', PACKAGE = 'sptpsar', x)
}

Ainv <- function(x) {
    .Call('_sptpsar_Ainv', PACKAGE = 'sptpsar', x)
}

AtAsp <- function(x) {
    .Call('_sptpsar_AtAsp', PACKAGE = 'sptpsar', x)
}

lltAsp <- function(x) {
    .Call('_sptpsar_lltAsp', PACKAGE = 'sptpsar', x)
}

detlltAsp <- function(x) {
    .Call('_sptpsar_detlltAsp', PACKAGE = 'sptpsar', x)
}

ldetluAsp <- function(x) {
    .Call('_sptpsar_ldetluAsp', PACKAGE = 'sptpsar', x)
}

